--Operadores Relacionais

local var1 = 5 == 5 --Equivalencia
local var2 = 5 ~= 6 --Diferente de...

local var3 = 5 > 10 --Maior que...
local var4 = 5 < 10 --Menor que...

local var5 = 5 >= 10 --Maior ou igual que...
local var6 = 5 <= 10 --Menor ou igual que...

print(var6)